# If set to true, JDS require JDC to reveal the transactions they are going to mine on
full_template_mode_required = true

# SRI Pool config
authority_public_key = "9auqWEzQDVyd2oe1JVGFLMLHZtCo2FFqZwtKA5gd9xbuEu7PH72"
authority_secret_key = "mkDLTBBRxdBv998612qipDYoTK3YUrqLe8uWw7gu3iXbSrn2n"
cert_validity_sec = 3600

# List of coinbase outputs used to build the coinbase tx
# ! Right now only one output is supported, so comment all the ones you don't need !
# For P2PK, P2PKH, P2WPKH, P2TR a public key is needed. For P2SH and P2WSH, a redeem script is needed.
coinbase_outputs = [
    { output_script_type = "P2WPKH", output_script_value = "fixme" },
]

# SRI Pool JD config
listen_jd_address = "0.0.0.0:34264"

# RPC config for mempool (it can be also the same TP if correctly configured)
core_rpc_url =  "http://127.0.0.1"
core_rpc_port = 38332
core_rpc_user =  "username"
core_rpc_pass =  "password"
# Time interval used for JDS mempool update
[mempool_update_interval]
unit = "secs"
value = 1
