[package]
name = "binary_sv2"
version = "2.0.0"
authors = ["The Stratum V2 Developers"]
edition = "2018"
readme = "README.md"
description = "Sv2 data format"
documentation = "https://docs.rs/binary_sv2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stratum-mining/stratum"
homepage = "https://stratumprotocol.org"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_codec_sv2 = { path = "codec" }
derive_codec_sv2 = { path = "derive_codec" }

[features]
prop_test = ["binary_codec_sv2/prop_test"]
with_buffer_pool = ["binary_codec_sv2/with_buffer_pool"]

[package.metadata.docs.rs]
features = ["with_buffer_pool"]
