coverage:
  status:
    project:
      default:
        target: auto
        threshold: 100%
        base: auto
        informational: false
    patch:
      default:
        target: auto
        threshold: 100%
        base: auto
github_checks:
    annotations: false
