// # Initiator Role
//
// Manages the [`Initiator`] role in the Noise protocol handshake for communication between Sv2
// roles. The initiator is responsible for starting the handshake process by sending the first
// cryptographic message to the [`crate::Responder`] role (e.g., a mining pool).
//
// The [`Initiator`] role is equipped with utilities for generating and managing the initiator's
// key pairs, performing elliptic curve Diffie-Hellman (ECDH) key exchanges, and encrypting
// messages during the handshake phase. The initiator's responsibilities include:
//
// - Generating an ephemeral key pair for the handshake.
// - Using the [`secp256k1`] elliptic curve for ECDH to derive a shared secret.
// - Encrypting the initial handshake message to securely exchange cryptographic material.
// - Managing the state transitions between handshake steps, including updating the handshake hash,
//   chaining key, and encryption key as the session progresses.
//
// ## Usage
// The initiator role is typically used by a downstream Sv2 role (e.g., a local mining proxy) to
// establish a secure connection with an upstream responder (e.g., a remote mining pool). The
// initiator begins the handshake by generating a public key and sending it to the responder. After
// receiving a response, the initiator computes a shared secret and encrypts further messages using
// this key.
//
// The [`Initiator`] struct implements the [`HandshakeOp`] trait, which defines the core
// cryptographic operations during the handshake. It ensures secure communication by supporting
// the [`ChaCha20Poly1305`] cipher, providing both confidentiality and message authentication for
// all subsequent communication.
//
// ### Secure Data Erasure
//
// The [`Initiator`] includes functionality for securely erasing sensitive cryptographic material,
// ensuring that private keys and other sensitive data are wiped from memory when no longer needed.
//
// The [`Drop`] trait is implemented to automatically trigger secure erasure when the [`Initiator`]
// instance goes out of scope, preventing potential misuse or leakage of cryptographic material.

use alloc::{
    boxed::Box,
    string::{String, ToString},
};
use core::convert::TryInto;
use zeroize::Zeroize;

use crate::{
    cipher_state::{Cipher, CipherState},
    error::Error,
    handshake::HandshakeOp,
    signature_message::SignatureNoiseMessage,
    AeadError, NoiseEngine, ELLSWIFT_ENCODING_SIZE, ENCRYPTED_ELLSWIFT_ENCODING_SIZE,
    ENCRYPTED_SIGNATURE_NOISE_MESSAGE_SIZE, INITIATOR_EXPECTED_HANDSHAKE_MESSAGE_SIZE,
    SIGNATURE_NOISE_MESSAGE_SIZE,
};
use chacha20poly1305::{ChaCha20Poly1305, Key, KeyInit};
use secp256k1::{
    ellswift::{ElligatorSwift, ElligatorSwiftParty},
    Keypair, PublicKey, XOnlyPublicKey,
};

/// Manages the initiator's role in the Noise NX handshake, handling key exchange, encryption, and
/// handshake state. It securely generates and manages cryptographic keys, performs Diffie-Hellman
/// exchanges, and maintains the handshake hash, chaining key, and nonce for message encryption.
/// After the handshake, it facilitates secure communication using [`ChaCha20Poly1305`]. Sensitive
/// data is securely erased when no longer needed.
pub struct Initiator {
    // Cipher used for encrypting and decrypting messages during the handshake.
    //
    // It is initialized once enough information is available from the handshake process.
    handshake_cipher: Option<ChaCha20Poly1305>,
    // Optional static key used in the handshake. This key may be derived from the pre-shared key
    // (PSK) or generated during the handshake.
    k: Option<[u8; 32]>,
    // Current nonce used in the encryption process.
    //
    // Ensures that the same plaintext encrypted twice will produce different ciphertexts.
    n: u64,
    // Chaining key used in the key derivation process to generate new keys throughout the
    // handshake.
    ck: [u8; 32],
    // Handshake hash which accumulates all handshake messages to ensure integrity and prevent
    // tampering.
    h: [u8; 32],
    // Ephemeral key pair generated by the initiator for this session, used for generating the
    // shared secret with the responder.
    e: Keypair,
    // Optional authority public key of the responder, used to verify the responder's certificate
    // during the handshake. `None` skips that verification entirely.
    #[allow(unused)]
    responder_authority_pk: Option<XOnlyPublicKey>,
}

impl core::fmt::Debug for Initiator {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("Initiator").finish()
    }
}

// Every handshake encryption goes through `encrypt_with_ad`, which takes `&mut self`, and
// `Initiator` is deliberately not `Clone`, so the handshake key and its nonce counter cannot be
// duplicated or advanced from two places at once. See `Cipher` for the transport-mode counterpart.
impl CipherState<ChaCha20Poly1305> for Initiator {
    fn get_k(&mut self) -> &mut Option<[u8; 32]> {
        &mut self.k
    }

    fn get_n(&self) -> u64 {
        self.n
    }

    fn set_n(&mut self, n: u64) {
        self.n = n;
    }

    fn get_cipher(&mut self) -> &mut Option<ChaCha20Poly1305> {
        &mut self.handshake_cipher
    }

    fn set_k(&mut self, k: Option<[u8; 32]>) {
        self.k = k;
    }
}

impl HandshakeOp<ChaCha20Poly1305> for Initiator {
    fn name(&self) -> String {
        "Initiator".to_string()
    }

    fn get_h(&mut self) -> &mut [u8; 32] {
        &mut self.h
    }

    fn get_ck(&mut self) -> &mut [u8; 32] {
        &mut self.ck
    }

    fn set_h(&mut self, data: [u8; 32]) {
        self.h = data;
    }

    fn set_ck(&mut self, data: [u8; 32]) {
        self.ck = data;
    }

    fn set_handshake_cipher(&mut self, cipher: ChaCha20Poly1305) {
        self.handshake_cipher = Some(cipher);
    }
}

impl Initiator {
    /// Creates a new [`Initiator`] instance with an optional responder authority public key.
    ///
    /// If the responder authority public key is provided, the initiator uses this key to
    /// authenticate the responder during the handshake: the certificate received in
    /// [`Self::step_2`] must be signed by this key and be inside its validity window, otherwise
    /// the handshake fails with [`Error::InvalidCertificate`]. The initial initiator state is
    /// instantiated with the ephemeral key pair and handshake hash.
    ///
    /// # Security
    ///
    /// Passing `None` disables responder authentication. The handshake then accepts any peer,
    /// and the resulting session is encrypted but not authenticated. It is also indistinguishable
    /// from an authenticated one, since [`Self::step_2`] returns `Ok` in both cases. Prefer
    /// [`Self::without_pk`] when this is intended, so that the choice is visible at the call site,
    /// and read its documentation for the consequences.
    #[cfg(feature = "std")]
    pub fn new(pk: Option<XOnlyPublicKey>) -> Box<Self> {
        Self::new_with_rng(pk, &mut rand::thread_rng())
    }

    /// Creates a new [`Initiator`] instance with an optional responder public key and a custom
    /// random number generator.
    ///
    /// See [`Self::new`] for more details.
    ///
    /// The custom random number generator is used to generate the ephemeral key pair. It should be
    /// provided in order to not implicitely rely on `std` and allow `no_std` environments to
    /// provide a hardware random number generator for example.
    #[inline]
    pub fn new_with_rng<R: rand::Rng + rand::CryptoRng + ?Sized>(
        pk: Option<XOnlyPublicKey>,
        rng: &mut R,
    ) -> Box<Self> {
        let mut self_ = Self {
            handshake_cipher: None,
            k: None,
            n: 0,
            ck: [0; 32],
            h: [0; 32],
            e: Self::generate_key_with_rng(rng),
            responder_authority_pk: pk,
        };
        self_.initialize_self();
        Box::new(self_)
    }

    /// Creates a new [`Initiator`] instance using a raw 32-byte public key.
    ///
    /// Constructs a [`XOnlyPublicKey`] from the provided raw key slice and initializes a new
    /// [`Initiator`] with the derived public key. If the provided key cannot be converted into a
    /// valid [`XOnlyPublicKey`], an [`Error::InvalidRawPublicKey`] error is returned.
    ///
    /// Typically used when the initiator is aware of the responder's public key in advance.
    #[cfg(feature = "std")]
    pub fn from_raw_k(key: [u8; 32]) -> Result<Box<Self>, Error> {
        Self::from_raw_k_with_rng(key, &mut rand::thread_rng())
    }

    /// Creates a new [`Initiator`] instance using a raw 32-byte public key and a custom random
    /// number generator.
    ///
    /// See [`Self::from_raw_k`] for more details.
    ///
    /// The custom random number generator should be provided in order to not implicitely rely on
    /// `std` and allow `no_std` environments to provide a hardware random number generator for
    /// example.
    #[inline]
    pub fn from_raw_k_with_rng<R: rand::Rng + rand::CryptoRng + ?Sized>(
        key: [u8; 32],
        rng: &mut R,
    ) -> Result<Box<Self>, Error> {
        let pk =
            secp256k1::XOnlyPublicKey::from_slice(&key).map_err(|_| Error::InvalidRawPublicKey)?;
        Ok(Self::new_with_rng(Some(pk), rng))
    }

    /// Creates a new [`Initiator`] that does not authenticate the responder.
    ///
    /// # Security
    ///
    /// The responder's certificate is not verified: its signature, its validity window and the
    /// authority that issued it are all ignored, so any peer that completes the Noise NX
    /// handshake is accepted. The session is still encrypted, which protects against passive
    /// eavesdropping, but an active attacker on the path can impersonate the responder or sit
    /// between the two roles and read or rewrite every message.
    ///
    /// Nothing in the returned [`NoiseEngine`] records that the responder was not authenticated,
    /// and [`Self::step_2`] returns `Ok` exactly as it does for a verified session. Callers that
    /// need to tell the two apart must track which constructor they used.
    ///
    /// Only use this constructor when the initiator and responder are on the same trusted network
    /// and the responder has no authority key to pin. Whenever the responder's authority public
    /// key is available, use [`Self::new`] with `Some(key)` or [`Self::from_raw_k`] instead.
    #[cfg(feature = "std")]
    pub fn without_pk() -> Result<Box<Self>, Error> {
        Self::without_pk_with_rng(&mut rand::thread_rng())
    }

    /// Creates a new [`Initiator`] that does not authenticate the responder, using a custom
    /// random number generator.
    ///
    /// See [`Self::without_pk`] for more details, including the security consequences of
    /// skipping responder authentication.
    ///
    /// The custom random number generator should be provided in order to not implicitely rely on
    /// `std` and allow `no_std` environments to provide a hardware random number generator for
    /// example.
    #[inline]
    pub fn without_pk_with_rng<R: rand::Rng + rand::CryptoRng + ?Sized>(
        rng: &mut R,
    ) -> Result<Box<Self>, Error> {
        Ok(Self::new_with_rng(None, rng))
    }

    /// Executes the initial step of the Noise NX protocol handshake.
    ///
    /// This step involves generating an ephemeral keypair and encoding the public key using
    /// Elligator Swift encoding, which obscures the key to prevent identification. The encoded
    /// public key is then mixed into the handshake state, and an empty payload is encrypted.
    /// This operation currently only affects the handshake hash, as the key (`k`) is not yet
    /// established. The function returns the encoded public key, which is ready to be sent to
    /// the responder.
    ///
    /// On success, the function returns a 64-byte array containing the encoded public key.
    /// If an error occurs during encryption, it returns an [`AeadError`].
    pub fn step_0(&mut self) -> Result<[u8; ELLSWIFT_ENCODING_SIZE], AeadError> {
        let elliswift_enc_pubkey = ElligatorSwift::from_pubkey(self.e.public_key()).to_array();
        self.mix_hash(&elliswift_enc_pubkey);
        self.encrypt_and_hash(&mut vec![])?;

        let mut message = [0u8; ELLSWIFT_ENCODING_SIZE];
        message[..64].copy_from_slice(&elliswift_enc_pubkey[..ELLSWIFT_ENCODING_SIZE]);
        Ok(message)
    }

    /// Processes the second step of the Noise NX protocol handshake for the initiator.
    ///
    /// This method handles the responder's reply in the Noise NX protocol handshake, processing
    /// the message to derive shared secrets and authenticate the responder. It interprets the
    /// first 64 bytes of the message as the responder's ephemeral public key, decodes it, and
    /// mixes it into the handshake state. It then derives a shared secret from the ephemeral keys
    /// and updates the state accordingly.
    ///
    /// The next 80 bytes of the message contain the responder's static public key, encrypted and
    /// authenticated. The method decrypts this segment and derives another shared secret using the
    /// responder's static public key, further securing the handshake state. Finally, the method
    /// decrypts the certificate included in the message and, if this [`Initiator`] was built with
    /// a responder authority public key, verifies it to ensure the responder's authenticity.
    ///
    /// On success, this method returns a [`NoiseEngine`] instance initialized with session ciphers
    /// for secure communication. If the provided `message` has an incorrect length, it returns an
    /// [`Error::InvalidMessageLength`]. If decryption or signature verification fails, it returns
    /// an [`Error::InvalidCertificate`].
    ///
    /// # Security
    ///
    /// Without a responder authority public key (see [`Self::without_pk`]) the certificate is
    /// accepted unverified, and `Ok` does not mean the responder was authenticated. The returned
    /// [`NoiseEngine`] carries no indication of which case applies.
    ///
    /// On success the remaining handshake secrets, including the ephemeral keypair, are erased,
    /// so the [`Initiator`] cannot be used for another handshake.
    #[cfg(feature = "std")]
    pub fn step_2(
        &mut self,
        message: [u8; INITIATOR_EXPECTED_HANDSHAKE_MESSAGE_SIZE],
    ) -> Result<NoiseEngine, Error> {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs() as u32;
        self.step_2_with_now(message, now)
    }

    /// Processes the second step of the Noise NX protocol handshake for the initiator given the
    /// current system time.
    ///
    /// See [`Self::step_2`] for more details.
    ///
    /// The current system time should be provided to avoid relying on `std` and allow `no_std`
    /// environments to use another source of time.
    pub fn step_2_with_now(
        &mut self,
        message: [u8; INITIATOR_EXPECTED_HANDSHAKE_MESSAGE_SIZE],
        now: u32,
    ) -> Result<NoiseEngine, Error> {
        // 2. interprets first 64 bytes as ElligatorSwift encoding of x-coordinate of public key
        // from this is derived the 32-bytes remote ephemeral public key `re.public_key`
        let mut elliswift_theirs_ephemeral_serialized: [u8; ELLSWIFT_ENCODING_SIZE] =
            [0; ELLSWIFT_ENCODING_SIZE];
        elliswift_theirs_ephemeral_serialized.clone_from_slice(&message[0..ELLSWIFT_ENCODING_SIZE]);
        self.mix_hash(&elliswift_theirs_ephemeral_serialized);

        // 3. calls `MixHash(re.public_key)`
        // 4. calls `MixKey(ECDH(e.private_key, re.public_key))`
        let e_private_key = self.e.secret_key();
        let elligatorswift_ours_ephemeral = ElligatorSwift::from_pubkey(self.e.public_key());
        let elligatorswift_theirs_ephemeral =
            ElligatorSwift::from_array(elliswift_theirs_ephemeral_serialized);
        let mut ecdh_ephemeral: [u8; 32] = ElligatorSwift::shared_secret(
            elligatorswift_ours_ephemeral,
            elligatorswift_theirs_ephemeral,
            e_private_key,
            ElligatorSwiftParty::A,
            None,
        )
        .to_secret_bytes();
        self.mix_key(&ecdh_ephemeral);
        ecdh_ephemeral.zeroize();

        // 5. decrypts next 80 bytes with `DecryptAndHash()` and stores the results as
        // `rs.public_key` which is **server's static public key** (note that 64 bytes is the
        // elligatorswift encoded public key and 16 bytes is MAC)
        let mut to_decrypt = message
            [ELLSWIFT_ENCODING_SIZE..ELLSWIFT_ENCODING_SIZE + ENCRYPTED_ELLSWIFT_ENCODING_SIZE]
            .to_vec();
        self.decrypt_and_hash(&mut to_decrypt)?;

        // 6. calls `MixKey(ECDH(e.private_key, rs.public_key)`
        let elligatorswift_theirs_static_serialized: [u8; ELLSWIFT_ENCODING_SIZE] = to_decrypt[..]
            .try_into()
            .expect("slice with incorrect length");
        let elligatorswift_theirs_static =
            ElligatorSwift::from_array(elligatorswift_theirs_static_serialized);
        let mut ecdh_static: [u8; 32] = ElligatorSwift::shared_secret(
            elligatorswift_ours_ephemeral,
            elligatorswift_theirs_static,
            e_private_key,
            ElligatorSwiftParty::A,
            None,
        )
        .to_secret_bytes();
        self.mix_key(&ecdh_static);
        ecdh_static.zeroize();

        // Decrypt and verify the SignatureNoiseMessage
        let mut to_decrypt = message[ELLSWIFT_ENCODING_SIZE + ENCRYPTED_ELLSWIFT_ENCODING_SIZE
            ..INITIATOR_EXPECTED_HANDSHAKE_MESSAGE_SIZE]
            .to_vec();
        if to_decrypt.len() != ENCRYPTED_SIGNATURE_NOISE_MESSAGE_SIZE {
            return Err(Error::InvalidMessageLength);
        }

        self.decrypt_and_hash(&mut to_decrypt)?;
        let plaintext: [u8; SIGNATURE_NOISE_MESSAGE_SIZE] = to_decrypt.try_into().unwrap();
        let signature_message: SignatureNoiseMessage = plaintext.into();
        let rs_pub_key = PublicKey::from_ellswift(elligatorswift_theirs_static)
            .x_only_public_key()
            .0
            .serialize();
        let rs_pk_xonly = XOnlyPublicKey::from_slice(&rs_pub_key).unwrap();
        if signature_message.verify_with_now(&rs_pk_xonly, &self.responder_authority_pk, now) {
            let (mut temp_k1, mut temp_k2) = Self::hkdf_2(self.get_ck(), &[]);
            let c1 = ChaCha20Poly1305::new(Key::from_slice(&temp_k1[..]));
            let c2 = ChaCha20Poly1305::new(Key::from_slice(&temp_k2[..]));
            let c1: Cipher<ChaCha20Poly1305> = Cipher::from_key_and_cipher(temp_k1, c1);
            let c2: Cipher<ChaCha20Poly1305> = Cipher::from_key_and_cipher(temp_k2, c2);
            let mut encryptor = c1;
            let mut decryptor = c2;
            encryptor.erase_k();
            decryptor.erase_k();
            // The ciphers keep the only copies of the session keys from here on; `erase_k` above
            // wiped the copies the `Cipher`s carried, and these are the ones the handshake used.
            temp_k1.zeroize();
            temp_k2.zeroize();
            let engine = crate::NoiseEngine {
                encryptor,
                decryptor,
            };
            self.erase();
            Ok(engine)
        } else {
            Err(Error::InvalidCertificate(plaintext.into()))
        }
    }

    // Securely erases sensitive data from the [`Initiator`] memory.
    //
    // Zeroizes the handshake key (`k`), the chaining key (`ck`) and the handshake
    // hash (`h`), and non-securely erases the ephemeral keypair. This method is typically called
    // when the [`Initiator`] instance is no longer needed or before deallocation.
    //
    // It does not touch `handshake_cipher`: that key is wiped by [`ChaCha20Poly1305`]'s own
    // zeroize-on-drop. Nor does it reach the transport session ciphers, which by then live in the
    // [`NoiseEngine`] returned by [`Self::step_2`] and are wiped when that is dropped.
    fn erase(&mut self) {
        self.handshake_cipher = None;
        self.k.zeroize();
        self.ck.zeroize();
        self.h.zeroize();
        self.e.non_secure_erase();
    }
}
impl Drop for Initiator {
    fn drop(&mut self) {
        self.erase();
    }
}

#[cfg(test)]
mod test {

    use super::*;

    #[test]
    #[cfg_attr(miri, ignore)]
    fn initiator_step0_produces_elligator_message() {
        let mut initiator = Initiator::without_pk().unwrap();

        let msg = initiator.step_0().expect("step_0 must succeed");

        assert_eq!(msg.len(), ELLSWIFT_ENCODING_SIZE);
        assert!(msg.iter().any(|b| *b != 0));
    }

    #[test]
    #[cfg(feature = "std")]
    #[cfg_attr(miri, ignore)]
    fn initiator_erase_zeroes_ck_and_h() {
        let mut initiator = Initiator::without_pk().unwrap();
        assert!(initiator.ck.iter().any(|b| *b != 0));
        assert!(initiator.h.iter().any(|b| *b != 0));

        initiator.erase();

        assert_eq!(initiator.ck, [0u8; 32]);
        assert_eq!(initiator.h, [0u8; 32]);
    }

    #[test]
    #[cfg(feature = "std")]
    #[cfg_attr(miri, ignore)]
    fn initiator_rejects_tampered_handshake() {
        use crate::Responder;

        let authority_kp = Responder::generate_key();
        let mut responder = Responder::new(authority_kp, 60);
        let mut initiator = Initiator::without_pk().unwrap();

        let msg0 = initiator.step_0().unwrap();
        let (mut msg1, _) = responder.step_1(msg0).unwrap();

        let idx = INITIATOR_EXPECTED_HANDSHAKE_MESSAGE_SIZE - 5;
        msg1[idx] ^= 0x01;

        let res = initiator.step_2(msg1);
        assert!(res.is_err());
    }

    #[test]
    #[cfg(feature = "std")]
    #[cfg_attr(miri, ignore)]
    fn initiator_step_2_erases_handshake_secrets() {
        use crate::Responder;

        let authority_kp = Responder::generate_key();
        let mut responder = Responder::new(authority_kp, 60);
        let mut initiator = Initiator::without_pk().unwrap();
        let ephemeral_before = initiator.e.secret_key().secret_bytes();

        let msg0 = initiator.step_0().unwrap();
        let (msg1, _) = responder.step_1(msg0).unwrap();
        let _engine = initiator.step_2(msg1).unwrap();

        assert_ne!(initiator.e.secret_key().secret_bytes(), ephemeral_before);
        assert_eq!(initiator.ck, [0u8; 32]);
        assert_eq!(initiator.h, [0u8; 32]);
    }
}
