name: Clippy Lint

on:
  pull_request:
    branches: [main]

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, 1.75]

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
          components: clippy
      - name: Run Clippy on different workspaces and crates
        run: ./scripts/rust/clippy.sh
