on:
  pull_request:
    branches:
      - main

name: Clippy Checks

jobs:
  clippy-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy on benches workspace
        run: |
          cargo clippy --manifest-path=benches/Cargo.toml -- -D warnings -A dead-code

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy on core workspace
        run: |
          cargo clippy --manifest-path=common/Cargo.toml -- -D warnings -A dead-code

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy on protocol workspace
        run: |
          cargo clippy --manifest-path=protocols/Cargo.toml -- -D warnings -A dead-code

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy on roles workspace
        run: |
          cargo clippy --manifest-path=roles/Cargo.toml -- -D warnings -A dead-code

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy on utils workspace
        run: |
          cargo clippy --manifest-path=utils/Cargo.toml -- -D warnings -A dead-code
