name: Util Test Coverage

on:
  push:
    branches:
      - main

jobs:
  utils-coverage:

    name: tarpaulin Test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:0.27.1-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          ./scripts/coverage-utils.sh

      - name: Upload utils coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./utils/target/tarpaulin-reports
          file: ./utils/target/tarpaulin-reports/cobertura.xml
          flags: utils
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload bip32_derivation-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./utils/target/tarpaulin-reports/bip32-key-derivation-coverage
          file: ./utils/target/tarpaulin-reports/bip32-key-derivation-coverage/cobertura.xml
          flags: bip32_derivation-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload buffer_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./utils/target/tarpaulin-reports/buffer-coverage
          file: ./utils/target/tarpaulin-reports/buffer-coverage/cobertura.xml
          flags: buffer_sv2-coverage
          
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload error_handling-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./utils/target/tarpaulin-reports/error-handling-coverage
          file: ./utils/target/tarpaulin-reports/error-handling-coverage/cobertura.xml
          flags: error_handling-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload key-utils-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./utils/target/tarpaulin-reports/key-utils-coverage
          file: ./utils/target/tarpaulin-reports/key-utils-coverage/cobertura.xml
          flags: key-utils-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
