name: Roles test Coverage

on:
  push:
    branches:
      - main

jobs:
  roles-coverage:

    name: tarpaulin Test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:0.27.1-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate code coverage
        run: |
          ./scripts/coverage-roles.sh

      - name: Upload roles coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports
          file: ./roles/target/tarpaulin-reports/cobertura.xml
          flags: roles
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload jd_client-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports/jd-client-coverage
          file: ./roles/target/tarpaulin-reports/jd-client-coverage/cobertura.xml
          flags: jd_client-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload jd_server-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports/jd-server-coverage
          file: ./roles/target/tarpaulin-reports/jd-server-coverage/cobertura.xml
          flags: jd_server-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload mining_device-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports/mining-device-coverage
          file: ./rroles/target/tarpaulin-reports/mining-device-coverage/cobertura.xml
          flags: mining_device-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload pool_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports/pool-coverage
          file: ./roles/target/tarpaulin-reports/pool-coverage/cobertura.xml
          flags: pool_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload sv1-mining-device-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports/sv1-mining-device-coverage
          file: ./roles/target/tarpaulin-reports/sv1-mining-device-coverage/cobertura.xml
          flags: sv1-mining-device-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload translator_sv2-coverage to codecov.io
        uses: codecov/codecov-action@v4
        with:
          directory: ./roles/target/tarpaulin-reports/translator-coverage
          file: ./roles/target/tarpaulin-reports/translator-coverage/cobertura.xml
          flags: translator_sv2-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
