//! These byte-sequence generators are based on the Stratim V2 specification.
//!
//! They MUST aim to reflect the behavior described in the specification.
//! The generated byte sequences MUST always be parseable by the corresponding
//! `from_bytes` implementation for each type.
//!
//! If parsing fails, it may indicate a bug in the SRI implementation, an issue
//! in the generators themselves, or a discrepancy between the implementation
//! and the specification.
//!
//! These generators are based on the current main branch of the Stratum V2
//! specification at revision: 0925350f0aec36d15205bb87e0589c999c04b15f
#![allow(dead_code)]

use arbitrary::Unstructured;


/// Generates a random-length byte payload with a maximum size of `max`.
///
/// The actual payload length is chosen by the fuzzer and may be anywhere
/// from 0 to `max`. If fewer than `max` bytes remain in the fuzzer input,
/// the available input size is used as the upper bound instead.
///
/// Let's say, if 10 bytes remain and `max` is 32, the function will
/// choose a length between 0 and 10. This prevents requesting more bytes
/// than are available and avoids unnecessary parsing failures.
fn gen_var_payload(u: &mut Unstructured, max: usize) -> arbitrary::Result<Vec<u8>> {
    let cap = u.len().min(max);
    let len = u.int_in_range(0..=cap)?;
    Ok(u.bytes(len)?.to_vec())
}

// ---------------------------------------------------------------------------
// Fixed-size primitive (LE encoding)
// ---------------------------------------------------------------------------
pub fn gen_u8(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.arbitrary::<u8>()?.to_le_bytes().to_vec())
}

pub fn gen_u16(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.arbitrary::<u16>()?.to_le_bytes().to_vec())
}

pub fn gen_u32(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.arbitrary::<u32>()?.to_le_bytes().to_vec())
}

pub fn gen_u64(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.arbitrary::<u64>()?.to_le_bytes().to_vec())
}

pub fn gen_f32(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.arbitrary::<f32>()?.to_le_bytes().to_vec())
}

// the bool type has a weird behavior where we should only look at the 
// LEAST SIGNIFICANT BIT; but this behavior will be fuzzed in the macros.
// Here I just generate canonical u8;
pub fn gen_bool(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(vec![u.arbitrary::<bool>()? as u8])
}

pub fn gen_u24(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let raw = u.int_in_range(0u32..=0x00FF_FFFF)?;
    let b = raw.to_le_bytes();
    Ok(vec![b[0], b[1], b[2]]) 
}

pub fn gen_u256(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.bytes(32)?.to_vec())
}

pub fn gen_pubkey(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.bytes(32)?.to_vec())
}

pub fn gen_signature(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    Ok(u.bytes(64)?.to_vec())
}

// ---------------------------------------------------------------------------
// Variable-length byte arrays (length-prefixed)
// ---------------------------------------------------------------------------

pub fn gen_b032(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let payload = gen_var_payload(u, 32)?;
    let mut buf = Vec::with_capacity(1 + payload.len());
    buf.push(payload.len() as u8);
    buf.extend_from_slice(&payload);
    Ok(buf)
}

pub fn gen_b0255(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let payload = gen_var_payload(u, 255)?;
    let mut buf = Vec::with_capacity(1 + payload.len());
    buf.push(payload.len() as u8);
    buf.extend_from_slice(&payload);
    Ok(buf)
}

pub fn gen_str0255(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let payload = gen_var_payload(u, 255)?;
    let mut buf = Vec::with_capacity(1 + payload.len());
    buf.push(payload.len() as u8);
    buf.extend_from_slice(&payload);
    Ok(buf)
}

/// Capped at 512 bytes of payload for tractable fuzzer corpus sizes.
pub fn gen_b064k(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let payload = gen_var_payload(u, 512)?;
    let len = payload.len() as u16;
    let mut buf = Vec::with_capacity(2 + payload.len());
    buf.extend_from_slice(&len.to_le_bytes());
    buf.extend_from_slice(&payload);
    Ok(buf)
}

/// Capped at 100 bytes of payload for tractable fuzzer corpus sizes.
pub fn gen_b016m(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let payload = gen_var_payload(u, 100)?;
    let len = payload.len() as u32;
    let b = len.to_le_bytes();
    let mut buf = Vec::with_capacity(3 + payload.len());
    buf.extend_from_slice(&b[..3]); // 3 bytes LE
    buf.extend_from_slice(&payload);
    Ok(buf)
}

// ---------------------------------------------------------------------------
// Nested Types
// ---------------------------------------------------------------------------

pub fn gen_seq0255(
    u: &mut Unstructured,
    gen_elem: impl FnMut(&mut Unstructured) -> arbitrary::Result<Vec<u8>>,
    max_count: usize,
) -> arbitrary::Result<Vec<u8>> {
    let mut gen_elem = gen_elem;
    let count = u.int_in_range(0..=max_count.min(255))?;
    let mut buf = Vec::with_capacity(1 + count * 32);
    buf.push(count as u8);
    for _ in 0..count {
        buf.extend_from_slice(&gen_elem(u)?);
    }
    Ok(buf)
}

pub fn gen_seq064k(
    u: &mut Unstructured,
    gen_elem: impl FnMut(&mut Unstructured) -> arbitrary::Result<Vec<u8>>,
    max_count: usize,
) -> arbitrary::Result<Vec<u8>> {
    let mut gen_elem = gen_elem;
    let count = u.int_in_range(0..=max_count.min(65535))?;
    let mut buf = Vec::with_capacity(2 + count * 32);
    buf.extend_from_slice(&(count as u16).to_le_bytes());
    for _ in 0..count {
        buf.extend_from_slice(&gen_elem(u)?);
    }
    Ok(buf)
}

pub fn gen_sv2_option(
    u: &mut Unstructured,
    mut gen_elem: impl FnMut(&mut Unstructured) -> arbitrary::Result<Vec<u8>>,
) -> arbitrary::Result<Vec<u8>> {
    if u.arbitrary::<bool>()? {
        let mut buf = vec![1u8];
        buf.extend_from_slice(&gen_elem(u)?);
        Ok(buf)
    } else {
        Ok(vec![0u8])
    }
}

// ============================================================================
// Common Messages
// ============================================================================

pub fn gen_setup_connection(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(128);
    buf.push(u.int_in_range(0u8..=2)?); // protocol (valid discriminant only)
    buf.extend_from_slice(&u.arbitrary::<u16>()?.to_le_bytes()); // min_version
    buf.extend_from_slice(&u.arbitrary::<u16>()?.to_le_bytes()); // max_version
    buf.extend_from_slice(&u.arbitrary::<u32>()?.to_le_bytes()); // flags
    buf.extend_from_slice(&gen_str0255(u)?); // endpoint_host
    buf.extend_from_slice(&u.arbitrary::<u16>()?.to_le_bytes()); // endpoint_port
    buf.extend_from_slice(&gen_str0255(u)?); // vendor
    buf.extend_from_slice(&gen_str0255(u)?); // hardware_version
    buf.extend_from_slice(&gen_str0255(u)?); // firmware
    buf.extend_from_slice(&gen_str0255(u)?); // device_id
    Ok(buf)
}

pub fn gen_setup_connection_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&u.arbitrary::<u32>()?.to_le_bytes()); // flags
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    Ok(buf)
}

pub fn gen_setup_connection_success(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(6);
    buf.extend_from_slice(&u.arbitrary::<u16>()?.to_le_bytes()); // used_version
    buf.extend_from_slice(&u.arbitrary::<u32>()?.to_le_bytes()); // flags
    Ok(buf)
}

pub fn gen_reconnect(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_str0255(u)?); // new_host
    buf.extend_from_slice(&u.arbitrary::<u16>()?.to_le_bytes()); // new_port
    Ok(buf)
}

pub fn gen_channel_endpoint_changed(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    gen_u32(u) // channel_id
}

// ============================================================================
// Job Declaration Messages
// ============================================================================

pub fn gen_allocate_mining_job_token(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_str0255(u)?); // user_identifier
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    Ok(buf)
}

pub fn gen_allocate_mining_job_token_success(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_b0255(u)?); // mining_job_token
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_outputs
    Ok(buf)
}

pub fn gen_declare_mining_job(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(256);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_b0255(u)?); // mining_job_token
    buf.extend_from_slice(&gen_u32(u)?); // version
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx_prefix
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx_suffix
    buf.extend_from_slice(&gen_seq064k(u, gen_u256, 256)?); // wtxid_list
    buf.extend_from_slice(&gen_b064k(u)?); // excess_data
    Ok(buf)
}

pub fn gen_declare_mining_job_success(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_b0255(u)?); // new_mining_job_token
    Ok(buf)
}

pub fn gen_declare_mining_job_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    buf.extend_from_slice(&gen_b064k(u)?); // error_details
    Ok(buf)
}

pub fn gen_provide_missing_transactions(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_seq064k(u, gen_u16, 256)?); // unknown_tx_position_list
    Ok(buf)
}

pub fn gen_provide_missing_transactions_success(
    u: &mut Unstructured,
) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    // intentionally capped
    buf.extend_from_slice(&gen_seq064k(u, gen_b016m, 10)?); // transaction_list.
    Ok(buf)
}

pub fn gen_push_solution(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(52);
    buf.extend_from_slice(&gen_b032(u)?); // extranonce
    buf.extend_from_slice(&gen_u256(u)?); // prev_hash
    buf.extend_from_slice(&gen_u32(u)?); // nonce
    buf.extend_from_slice(&gen_u32(u)?); // ntime
    buf.extend_from_slice(&gen_u32(u)?); // nbits
    buf.extend_from_slice(&gen_u32(u)?); // version
    Ok(buf)
}

// ============================================================================
// Mining Messages
// ============================================================================

pub fn gen_close_channel(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_str0255(u)?); // reason_code
    Ok(buf)
}

pub fn gen_new_mining_job(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(48);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // job_id
    buf.extend_from_slice(&gen_sv2_option(u, gen_u32)?); // min_ntime
    buf.extend_from_slice(&gen_u32(u)?); // version
    buf.extend_from_slice(&gen_u256(u)?); // merkle_root
    Ok(buf)
}

pub fn gen_new_extended_mining_job(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(128);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // job_id
    buf.extend_from_slice(&gen_sv2_option(u, gen_u32)?); // min_ntime
    buf.extend_from_slice(&gen_u32(u)?); // version
    buf.extend_from_slice(&gen_bool(u)?); // version_rolling_allowed
    buf.extend_from_slice(&gen_seq0255(u, gen_u256, 255)?); // merkle_path
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx_prefix
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx_suffix
    Ok(buf)
}

pub fn gen_open_standard_mining_channel(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_str0255(u)?); // user_identity
    buf.extend_from_slice(&gen_f32(u)?); // nominal_hash_rate
    buf.extend_from_slice(&gen_u256(u)?); // max_target
    Ok(buf)

}
pub fn gen_open_standard_mining_channel_success(
    u: &mut Unstructured,
) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(72);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u256(u)?); // target
    buf.extend_from_slice(&gen_b032(u)?); // extranonce_prefix
    buf.extend_from_slice(&gen_u32(u)?); // group_channel_id
    Ok(buf)
}

pub fn gen_open_extended_mining_channel(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_str0255(u)?); // user_identity
    buf.extend_from_slice(&gen_f32(u)?); // nominal_hash_rate
    buf.extend_from_slice(&gen_u256(u)?); // max_target
    buf.extend_from_slice(&gen_u16(u)?); // min_extranonce_size
    Ok(buf)
}

pub fn gen_open_extended_mining_channel_success(
    u: &mut Unstructured,
) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(72);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u256(u)?); // target
    buf.extend_from_slice(&gen_u16(u)?); // extranonce_size
    buf.extend_from_slice(&gen_b032(u)?); // extranonce_prefix
    buf.extend_from_slice(&gen_u32(u)?); // group_channel_id
    Ok(buf)
}

pub fn gen_open_mining_channel_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    Ok(buf)
}

pub fn gen_set_custom_mining_job(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(256);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_b0255(u)?); // token
    buf.extend_from_slice(&gen_u32(u)?); // version
    buf.extend_from_slice(&gen_u256(u)?); // prev_hash
    buf.extend_from_slice(&gen_u32(u)?); // min_ntime
    buf.extend_from_slice(&gen_u32(u)?); // nbits
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_version
    buf.extend_from_slice(&gen_b0255(u)?); // coinbase_prefix
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_input_n_sequence
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx_outputs
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_locktime
    buf.extend_from_slice(&gen_seq0255(u, gen_u256, 255)?); // merkle_path
    Ok(buf)
}

pub fn gen_set_custom_mining_job_success(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(12);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_u32(u)?); // job_id
    Ok(buf)
}

pub fn gen_set_custom_mining_job_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // request_id
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    Ok(buf)
}

pub fn gen_set_extranonce_prefix(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(40);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_b032(u)?); // extranonce_prefix
    Ok(buf)
}
pub fn gen_set_group_channel(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u32(u)?); // group_channel_id
    buf.extend_from_slice(&gen_seq064k(u, gen_u32, 256)?); // channel_ids
    Ok(buf)
}

pub fn gen_set_new_prev_hash_mining(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(48);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // job_id
    buf.extend_from_slice(&gen_u256(u)?); // prev_hash
    buf.extend_from_slice(&gen_u32(u)?); // min_ntime
    buf.extend_from_slice(&gen_u32(u)?); // nbits
    Ok(buf)
}

pub fn gen_set_target(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(36);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u256(u)?); // maximum_target
    Ok(buf)
}

pub fn gen_submit_shares_standard(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(24);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // sequence_number
    buf.extend_from_slice(&gen_u32(u)?); // job_id
    buf.extend_from_slice(&gen_u32(u)?); // nonce
    buf.extend_from_slice(&gen_u32(u)?); // ntime
    buf.extend_from_slice(&gen_u32(u)?); // version
    Ok(buf)
}

pub fn gen_submit_shares_extended(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = gen_submit_shares_standard(u)?;
    buf.extend_from_slice(&gen_b032(u)?); // extranonce
    Ok(buf)
}

pub fn gen_submit_shares_success(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(16);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // last_sequence_number
    buf.extend_from_slice(&gen_u32(u)?); // new_submits_accepted_count
    buf.extend_from_slice(&gen_u64(u)?); // new_shares_sum
    Ok(buf)
}

pub fn gen_submit_shares_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_u32(u)?); // sequence_number
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    Ok(buf)
}

pub fn gen_update_channel(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(40);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_f32(u)?); // nominal_hash_rate
    buf.extend_from_slice(&gen_u256(u)?); // maximum_target
    Ok(buf)
}

pub fn gen_update_channel_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u32(u)?); // channel_id
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    Ok(buf)
}

// ============================================================================
// Template Distribution Messages
// ============================================================================

pub fn gen_coinbase_output_constraints(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(6);
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_output_max_additional_size
    buf.extend_from_slice(&gen_u16(u)?); // coinbase_output_max_additional_sigops
    Ok(buf)
}

pub fn gen_new_template(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(128);
    buf.extend_from_slice(&gen_u64(u)?); // template_id
    buf.extend_from_slice(&gen_bool(u)?); // future_template
    buf.extend_from_slice(&gen_u32(u)?); // version
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_version
    buf.extend_from_slice(&gen_b0255(u)?); // coinbase_prefix
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_input_sequence
    buf.extend_from_slice(&gen_u64(u)?); // coinbase_tx_value_remaining
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_outputs_count
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx_outputs
    buf.extend_from_slice(&gen_u32(u)?); // coinbase_tx_locktime
    buf.extend_from_slice(&gen_seq0255(u, gen_u256, 255)?); // merkle_path
    Ok(buf)
}

pub fn gen_request_transaction_data(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    gen_u64(u) //template_id
}

pub fn gen_request_transaction_data_success(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u64(u)?); // template_id
    buf.extend_from_slice(&gen_b064k(u)?); // excess_data
    // intentionally capped
    buf.extend_from_slice(&gen_seq064k(u, gen_b016m, 10)?); // transaction_list
    Ok(buf)
}

pub fn gen_request_transaction_data_error(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(32);
    buf.extend_from_slice(&gen_u64(u)?); // template_id
    buf.extend_from_slice(&gen_str0255(u)?); // error_code
    Ok(buf)
}

pub fn gen_set_new_prev_hash_template(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(52);
    buf.extend_from_slice(&gen_u64(u)?); // template_id
    buf.extend_from_slice(&gen_u256(u)?); // prev_hash
    buf.extend_from_slice(&gen_u32(u)?); // header_timestamp
    buf.extend_from_slice(&gen_u32(u)?); // n_bits
    buf.extend_from_slice(&gen_u256(u)?); // target
    Ok(buf)
}

pub fn gen_submit_solution(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let mut buf = Vec::with_capacity(64);
    buf.extend_from_slice(&gen_u64(u)?); // template_id
    buf.extend_from_slice(&gen_u32(u)?); // version
    buf.extend_from_slice(&gen_u32(u)?); // header_timestamp
    buf.extend_from_slice(&gen_u32(u)?); // header_nonce
    buf.extend_from_slice(&gen_b064k(u)?); // coinbase_tx
    Ok(buf)
}

// ---------------------------------------------------------------------------
// Frame generators
// ---------------------------------------------------------------------------

fn gen_message_payload(u: &mut Unstructured) -> arbitrary::Result<(u8, bool, Vec<u8>)> {
    let idx: u8 = u.int_in_range(0..=44)?;
    match idx {
        // Common messages (0x00..=0x04)
        0 => Ok((0x00, false, gen_setup_connection(u)?)),
        1 => Ok((0x01, false, gen_setup_connection_success(u)?)),
        2 => Ok((0x02, false, gen_setup_connection_error(u)?)),
        3 => Ok((0x03, true, gen_channel_endpoint_changed(u)?)),
        4 => Ok((0x04, false, gen_reconnect(u)?)),

        // Mining messages (0x10..=0x25)
        5 => Ok((0x10, false, gen_open_standard_mining_channel(u)?)),
        6 => Ok((0x11, false, gen_open_standard_mining_channel_success(u)?)),
        7 => Ok((0x12, false, gen_open_mining_channel_error(u)?)),
        8 => Ok((0x13, false, gen_open_extended_mining_channel(u)?)),
        9 => Ok((0x14, false, gen_open_extended_mining_channel_success(u)?)),
        10 => Ok((0x15, true, gen_new_mining_job(u)?)),
        11 => Ok((0x16, true, gen_update_channel(u)?)),
        12 => Ok((0x17, true, gen_update_channel_error(u)?)),
        13 => Ok((0x18, true, gen_close_channel(u)?)),
        14 => Ok((0x19, true, gen_set_extranonce_prefix(u)?)),
        15 => Ok((0x1a, true, gen_submit_shares_standard(u)?)),
        16 => Ok((0x1b, true, gen_submit_shares_extended(u)?)),
        17 => Ok((0x1c, true, gen_submit_shares_success(u)?)),
        18 => Ok((0x1d, true, gen_submit_shares_error(u)?)),
        // 0x1e is reserved (unsure why)
        19 => Ok((0x1f, true, gen_new_extended_mining_job(u)?)),
        20 => Ok((0x20, true, gen_set_new_prev_hash_mining(u)?)),
        21 => Ok((0x21, true, gen_set_target(u)?)),
        22 => Ok((0x22, true, gen_set_custom_mining_job(u)?)),
        23 => Ok((0x23, true, gen_set_custom_mining_job_success(u)?)),
        24 => Ok((0x24, true, gen_set_custom_mining_job_error(u)?)),
        25 => Ok((0x25, false, gen_set_group_channel(u)?)),

        // Job Declaration messages (0x50..=0x60)
        26 => Ok((0x50, false, gen_allocate_mining_job_token(u)?)),
        27 => Ok((0x51, false, gen_allocate_mining_job_token_success(u)?)),
        28 => Ok((0x55, false, gen_provide_missing_transactions(u)?)),
        29 => Ok((0x56, false, gen_provide_missing_transactions_success(u)?)),
        30 => Ok((0x57, false, gen_declare_mining_job(u)?)),
        31 => Ok((0x58, false, gen_declare_mining_job_success(u)?)),
        32 => Ok((0x59, false, gen_declare_mining_job_error(u)?)),
        33 => Ok((0x60, false, gen_push_solution(u)?)),

        // Template Distribution messages (0x70..=0x76)
        34 => Ok((0x70, false, gen_coinbase_output_constraints(u)?)),
        35 => Ok((0x71, false, gen_new_template(u)?)),
        36 => Ok((0x72, false, gen_set_new_prev_hash_template(u)?)),
        37 => Ok((0x73, false, gen_request_transaction_data(u)?)),
        38 => Ok((0x74, false, gen_request_transaction_data_success(u)?)),
        39 => Ok((0x75, false, gen_request_transaction_data_error(u)?)),
        40 => Ok((0x76, false, gen_submit_solution(u)?)),

        // Fallback: random payload for any remaining index
        _ => {
            let msg_type = u.int_in_range(0..=0x76)?;
            let payload_len: usize = u.int_in_range(0..=256)?;
            let payload = u.arbitrary::<Vec<u8>>()?.into_iter().take(payload_len).collect();
            let channel_msg = matches!(msg_type, 0x15..=0x24);
            Ok((msg_type, channel_msg, payload))
        }
    }
}

pub fn gen_sv2_frame(u: &mut Unstructured) -> arbitrary::Result<Vec<u8>> {
    let (msg_type, channel_msg, payload) = gen_message_payload(u)?;

    let extension_type: u16 = if channel_msg {
        u.int_in_range(0x8000..=0xFFFF)?
    } else {
        u.int_in_range(0x0000..=0x7FFF)?
    };

    let mut frame = Vec::with_capacity(6 + payload.len());
    frame.extend_from_slice(&extension_type.to_le_bytes());
    frame.push(msg_type);
    frame.extend_from_slice(&(payload.len() as u32).to_le_bytes()[..3]);
    frame.extend_from_slice(&payload);
    Ok(frame)
}
